project:
  type: website
  output-dir: docs
  

website:
  title: "Madison Enda"
  navbar:
    title: false 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources
      - text: Blog
        href: posts.qmd 
  page-footer: 
   background: light
   left: Copyright 2025, Madison Enda

format:
  html:
    theme: styles.scss
    mainfont: Quicksand 
    toc: false
    page-layout: full

editor: visual

