---
title: "About Me"
---

## **Education:**

### **M.S. in Environmental Data Science** (2024-2025)

-   This past summer I began my MS at UCSB, with the intention of honing my coding and data science skills for future research endeavors. Thus far, I have been able to improve my skills with R, Python, and Bash, as well as utilize GitHub to ensure reproducibility. I am especially excited to continue learning efficient methods for geospatial analysis.\
-   My current capstone project, entitled ‘Evaluating the protection of diverse and representative coastal and marine habitats within California’s Marine Protected Area (MPA) network, involves analyzing and compiling newly available biotic and substrate coverage data sets along the California coast. I am thrilled to play a role in this project, and cannot wait to present our report to our clients: CA Fish & Wildlife, the Monterey Bay Aquarium, and the California Ocean Protection Council.

### **B.S. in Marine Vertebrate Biology** (2019-2023)
- I recieved by BS in Marine Vertebrate Biology from Stony Brook University, NY, through the 'School of Marine & Atmospheric Sciences' (SOMAS)\
-   Within my major, I have been able to experience hands on methods of analyzing living specimens (both in situ and in lab) and collecting data for analysis.\
-   I am familiar with multiple titration methods, the use of spectrophotometers, dissolved oxygen meters, centrifuges, and basic distillation setups.\
-   Through biological and physical oceanography courses I have worked with CTDs (handheld and SeaBird), Niskin bottle sampling set ups, and other general methods for recording environmental data. I have collected and analyzed living specimens via trawl net collection or plankton tows, as well as diving to collect previously set up experiments.\
-   I also had the opportunity to increase my skillset in the field of marine rehabilitation through hands-on experience with high trophic level species at the New York Marine Rescue center, learning about the biology, behaviors, and typical treatment plans for various species of sea turtles, pinnipeds, and cetaceans.

### *Minor*: Coastal Environmental Studies

-This minor allowed me to narrow my research to coastal foundation species ecology.

### *Minor*: Ecosystems and Human Impact

-This minor allowed me to work with GIS programs and analysis, as well as environmental management and conservation policy.

### **Study Abroad: Coral Reefs of the Red Sea** (2022)

-   I was fortunate enough to be able to take part in a coral biology and conservation course in Eilat, Israel last summer! It was incredible to study the highly thermally tolerant reef, and to hear lectures from researchers traveling all over the world to develop plans for mitigating the major threats reefs face today.\
-   During this course I was able to observe many studies taking place at the ‘Interuniversity Institute for Marine Sciences of Eilat’. Some were analyzing the effects of light pollution on certain coral species, collecting eDNA samples for international databases, studying increased metabolic efficiency regarding pulsation rates of certain corals, and many others. I was able to study 3D modeling and the photogrammetry methods currently being employed by researchers there to conduct reef surveys or create artificial reefs with increased functional space.\
-   I hope to utilize the methods I learned to help me analyze and compile data for my future research projects. While studying here, I learned how to conduct transect line and grid surveys, use Agisoft Metashape Pro (and similar 3D imaging programs), collect coral tissue for analyzing, and how to set up basic coral life support systems

## **Experience:**

### **Teaching Assistant: Geographic Data Analysis** (Fall 2024)

-   I have just begun my assignment as a TA for GEOG 172: ‘Intermediate Geographic Data Analysis’ for the fall semester. My responsibilities include hosting a lab session, holding office hours, grading quizzes, labs, and proctoring exams\
-   I love interacting with my fellow students who share a love for geospatial science, and by grading coursework in MATLAB, I believe my students might even teach me more about coding along the way!

### **NIWC: Coral Reef Ecology \[Vieques, Puerto Rico\]** (2024)

-   Over the past few months, I was able to assist in a data science project involving ecological data from a reef restoration project in Vieques, Puerto Rico. Working with researchers at the Naval Information Warfare Center (NIWC) was an eye-opening experience, and I learned a lot about collaborative research with the goals of an organization or business in mind.\
-   With the help of my project mentor, I was able to identify patterns of species facilitation on artificial reefs suspended in the water column, and assess levels of biodiversity and habitat amelioration by the transplanted corals. I was surprised by some of the findings, and will keep them in mind for future reef restoration projects that involve coral nurseries, transplanting projects, or artificial substrate.

### **Coral Aquaculture Experience** (2023-2024)

-   In order to gain the necessary experience required to participate in a research lab, I have recently taken up a position in coral aquaculture! Through my daily tasks working at Cali Kid Corals in SoCal, I have learned how to care for a wide array of coral species, from hardy rhodactis, fungia, and zoathids, to delicate euphyillia, acropora, and goniopora.\
-   My work schedule included husbandry tasks (such as feeding, treating for disease and infestation, water changes, and checkups) as well as facility tasks (cleaning protein skimmers, tanks/water tables, changing RODI filters, and prepping fragging equipment). I believe that knowledge and training on such tasks play an important role in readying me to study marine life in future lab settings, and how to interpret responses in their biomass, coloration, or respiration rate.\
-   One of the most fascinating parts of my job (at least for me) was collecting water quality data, and maintaining constant salinity, pH, alkalinity, and nutrient levels. By analyzing fluctuations in coral growth, I am now able to predict which of the aforementioned factors needs to be adjusted, and this has greatly improved my overall understanding of how such changes would affect a marine ecosystem on a large scale.
